"""Table creations

Revision ID: 48ceb309ac59
Revises: 
Create Date: 2026-08-02 01:23:49.952793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ceb309ac59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday_type',
    sa.Column('holiday_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('holiday_description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_type'),
    schema='calendar'
    )
    op.create_table('student_class',
    sa.Column('class_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('section_name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name'),
    schema='calendar'
    )
    op.create_table('holiday',
    sa.Column('holiday_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('holiday_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('holiday_type_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_class_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['holiday_type_id'], ['calendar.holiday_type.id'], ),
    sa.ForeignKeyConstraint(['student_class_id'], ['calendar.student_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holiday', schema='calendar')
    op.drop_table('student_class', schema='calendar')
    op.drop_table('holiday_type', schema='calendar')
    # ### end Alembic commands ###
